version: '3.8'

services:
  db:
    container_name: thoughts-enhanced-db
    # pull image from docker hub
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: thoughts
      POSTGRES_USER: user
      POSTGRES_DB: thoughts_db
    ports:
      - 5432:5432
    volumes:
      -  thoughts-enhanced-db:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin-thoughts
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: example
    ports:
      - 8080:80
    depends_on:
      - db
    links:
      - db

  api:
    container_name: thoughts-enhanced-api
    # build image based on the server folder
    build: ./server
    restart: always
    ports:
      - 3001:3001
  
  web:
    container_name: thoughts-enhanced-web
    # build image based on the server folder
    build: .
    restart: always
    ports: 
      - 5173:5173

volumes:
  pgadmin-thoughts:
  thoughts-enhanced-db:
    driver: local
    # driver can be specified -> driver: local is default
    # volume will be created on the local filesystem of the docker host
    # data stored in the volume will persist once container is stopped/deleted


# defining services + telling docker how to build the specific images and how to run the images
# properties will be used when running the container
